### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by mcgov** [StanfordPL/stoke-release#24]
The links to your papers/presentations return 404 not found.
    Stochastic Superoptimization -- ASPLOS 2013 (link):
    Data-Driven Equivalence Checking -- OOPSLA 2013 (link):
    Stochastic Optimization of Floating-Point Programs with Tunable Precision -- PLDI 2014 (link):

**Comment by eschkufz** [comment]
This is due to me moving some stuff around on my old stanford homepage.

The links all point to cs.stanford.edu/people/eschkufz/research/...
That folder has changed to cs.stanford.edu/people/eschkufz/docs/...

Probably a longer term solution is to just copy the pdfs to the repository
and link to them directly.

While we're on the subject, we should add a link to the cove paper from
oopsla 2015.
